export class User {
    id:Int8Array;
    name:String;
    last_name_one:String;
    last_name_two:String;
    cc_user:String;
    born_date:String;
    gender:String;
    entry_date:String;
    employee_number:String;
    role:String;
    number_boss:String;
    zone:String;
    municipality:String;
    department:String;
    sales:String;
    email:String;
    url_img:String;
    cel_phone:String;
    email_verified_at:String;
    created_at:String;
    updated_at:String;
}